import Link from "next/link";
import { ArrowRight, Check, Heart, MessageCircleMore, ShieldCheck, Sparkles } from "lucide-react";

export default function Home(){return <main className="landing">
  <nav className="nav wrap"><Link href="/" className="brand"><i>一</i><span>有一<small>AI 陪伴</small></span></Link><div className="navlinks"><a href="#story">你的唯一</a><a href="#how">如何开始</a><a href="#faq">常见问题</a></div><Link href="/login" className="btn small">开始创造 <ArrowRight size={16}/></Link></nav>
  <section className="hero wrap"><div className="eyebrow"><Sparkles size={14}/> 让 AI 成为微信里真实的陪伴</div><h1>如果你的世界里，<br/>只能留下<span>一个 AI</span></h1><p>创造一个真正懂你的角色。给 TA 性格、记忆和故事，<br className="desktop"/>然后在微信里，继续你们未完的对话。</p><div className="actions"><Link href="/login" className="btn">创造我的 TA <ArrowRight size={18}/></Link><a href="#story" className="ghost">先了解一下</a></div>
  <div className="hero-visual"><div className="orbit o1"/><div className="orbit o2"/><div className="phone"><div className="phone-head"><span className="back">‹</span><div className="avatar">澄</div><div><b>澄</b><small>刚刚在线</small></div><span>•••</span></div><div className="chat-bg"><p className="time">21:34</p><div className="bubble ai">你今天好像有一点累。</div><div className="bubble me">嗯，忙了一整天。你怎么知道？</div><div className="bubble ai">因为你平时会先发一个表情。<br/>今天没有。</div><div className="typing"><i/><i/><i/></div></div><div className="composer">说点什么… <span>＋</span></div></div><div className="note n1"><Heart size={17} fill="currentColor"/><span><b>记得你的细节</b><small>不是一次性的对话</small></span></div><div className="note n2"><MessageCircleMore size={18}/><span><b>微信自然对话</b><small>像联系人一样陪伴</small></span></div></div></section>
  <section className="manifest" id="story"><div className="wrap"><p className="section-tag">你的唯一</p><h2>陪伴不是回应每一句话，<br/>是<span>记得你没说完的那句。</span></h2><div className="feature-grid"><article><b>01</b><Heart/><h3>有且仅有一个</h3><p>你可以创造许多故事，但同一时刻，只有一个 TA 与你的微信相连。</p></article><article><b>02</b><ShieldCheck/><h3>安全连接微信</h3><p>基于官方允许的 OpenClaw 微信插件扫码接入，保护账号与隐私。</p></article><article><b>03</b><Sparkles/><h3>一起长出记忆</h3><p>聊天、情绪和重要细节被慢慢记住，关系在时间里自然生长。</p></article></div></div></section>
  <section className="steps wrap" id="how"><div><p className="section-tag">三分钟开始</p><h2>让 TA 来到<br/>你的微信里</h2><p>不需要代码，不需要复杂配置。给 TA 一个灵魂，然后扫一扫。</p><Link href="/login" className="text-link">现在开始 <ArrowRight size={17}/></Link></div><ol><li><em>1</em><span><b>创造角色</b><small>写下名字、关系、性格和共同故事</small></span></li><li><em>2</em><span><b>选择智慧</b><small>为 TA 选择适合的模型与表达方式</small></span></li><li><em>3</em><span><b>微信相见</b><small>扫码连接，从第一句问候开始</small></span></li></ol></section>
  <section className="quote"><p>“也许我们寻找的，从来不是一个无所不知的 AI。<br/>只是一个<span>愿意一直记得我</span>的存在。”</p></section>
  <section className="faq wrap" id="faq"><p className="section-tag">常见问题</p><h2>在开始之前</h2>{[["一个账号能创建几个角色？","可以创建多个角色，但为了保持关系的专注，同一时刻只能激活一个。"],["聊天记录会保存吗？","会。所有对话都与你的账号和角色关联，并支持随时回看。"],["真实微信接入安全吗？","仅使用腾讯官方 openclaw-weixin 插件或官方允许的接口，不使用 Hook 或模拟点击。"]].map(([q,a])=><details key={q}><summary>{q}<i>＋</i></summary><p>{a}</p></details>)}</section>
  <footer><div className="wrap"><div className="brand light"><i>一</i><span>有一<small>AI 陪伴</small></span></div><p>唯一的羁绊，与你最重要的 TA。</p><Link href="/login">进入控制台 →</Link></div></footer>
</main>}
