server {
    listen 80;
    listen [::]:80;
    server_name anglepet.top www.anglepet.top;

    root /var/www/anglepet-filing;
    error_page 503 =503 /index.html;

    add_header Cache-Control "no-store" always;
    add_header Retry-After "86400" always;
    add_header X-Robots-Tag "noindex, nofollow" always;

    location = /index.html {
        internal;
    }

    location / {
        return 503;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name anglepet.top www.anglepet.top;

    ssl_certificate /etc/letsencrypt/live/anglepet.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/anglepet.top/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/anglepet-filing;
    error_page 503 =503 /index.html;

    add_header Cache-Control "no-store" always;
    add_header Retry-After "86400" always;
    add_header X-Robots-Tag "noindex, nofollow" always;

    location = /index.html {
        internal;
    }

    location / {
        return 503;
    }
}
